name: IDS-CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Cache node modules
      id: node-cache
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: node_modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          node-modules-

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: |
        yarn

    - name: Build
      run: |
        yarn build
        
    - name: Build:StoryBook
      run: |
        yarn build-storybook
        
    - name: Prettier Format Check
      run: |
        yarn run prettier
        
    - name: Lint Format Check
      run: |
        yarn run lint
        
    - name: Jest Integration Test
      run: |
        yarn test --passWithNoTests
